"""initial_schema"""

revision = '87511326a8b7'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_insights',
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('complaint_count', sa.Integer(), nullable=False),
    sa.Column('complaint_types', sa.JSON(), nullable=False),
    sa.Column('unique_users_reporting', sa.Integer(), nullable=False),
    sa.Column('complaint_frequency', sa.Float(), nullable=False),
    sa.Column('weakness_score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_insights'))
    )
    with op.batch_alter_table('competitor_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_insights_competitor_name'), ['competitor_name'], unique=True)

    op.create_table('contacts',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'CLOSED', name='contact_status'), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('groups',
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('invite_link', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('messages_last_24h', sa.Integer(), nullable=False),
    sa.Column('unique_users_last_24h', sa.Integer(), nullable=False),
    sa.Column('last_message_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('authority_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('discovery_source', sa.String(length=50), nullable=True),
    sa.Column('seller_density', sa.Float(), nullable=False),
    sa.Column('discussion_signal', sa.Integer(), nullable=False),
    sa.Column('saturation_status', sa.String(length=32), nullable=True),
    sa.Column('joined', sa.Boolean(), nullable=False),
    sa.Column('eligible_for_join', sa.Boolean(), nullable=False),
    sa.Column('date_discovered', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_scanned', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('metrics_snapshots',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('contacts_total', sa.Integer(), nullable=False),
    sa.Column('open_conversations', sa.Integer(), nullable=False),
    sa.Column('open_tickets', sa.Integer(), nullable=False),
    sa.Column('inbound_messages', sa.Integer(), nullable=False),
    sa.Column('outbound_messages', sa.Integer(), nullable=False),
    sa.Column('follow_ups_due', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_snapshots'))
    )
    with op.batch_alter_table('metrics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_snapshots_day'), ['day'], unique=True)

    op.create_table('personas',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('expertise', sa.String(length=255), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personas'))
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personas_name'), ['name'], unique=True)

    op.create_table('problem_trends',
    sa.Column('problem_type', sa.String(length=255), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_trends'))
    )
    op.create_table('telegram_accounts',
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('session_file', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('groups_joined', sa.Integer(), nullable=False),
    sa.Column('daily_dm_count', sa.Integer(), nullable=False),
    sa.Column('daily_reply_count', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('api_hash', sa.String(length=255), nullable=True),
    sa.Column('proxy_host', sa.String(length=255), nullable=True),
    sa.Column('proxy_port', sa.Integer(), nullable=True),
    sa.Column('proxy_type', sa.String(length=20), nullable=True),
    sa.Column('proxy_user', sa.String(length=255), nullable=True),
    sa.Column('proxy_pass', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_accounts'))
    )
    with op.batch_alter_table('telegram_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_accounts_phone_number'), ['phone_number'], unique=True)

    op.create_table('users',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('influence_level', sa.String(length=50), nullable=True),
    sa.Column('message_frequency', sa.Integer(), nullable=False),
    sa.Column('messages_today', sa.Integer(), nullable=False),
    sa.Column('groups_seen', sa.Integer(), nullable=False),
    sa.Column('complaints_count', sa.Integer(), nullable=False),
    sa.Column('technical_questions_count', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_power_user', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('activity_events',
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('USER_STARTED_CHAT', 'CONSENT_GRANTED', 'CONSENT_REVOKED', 'MESSAGE_RECEIVED', 'MESSAGE_SENT', 'TICKET_OPENED', 'TICKET_RESOLVED', 'FOLLOW_UP_QUEUED', 'FOLLOW_UP_CANCELLED', 'CONVERSATION_CLOSED', name='event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_activity_events_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_events'))
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('consents',
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'EMAIL', 'PHONE', name='consent_channel'), nullable=False),
    sa.Column('scope', sa.Enum('SUPPORT_UPDATES', 'DEMO_FOLLOW_UPS', 'PRODUCT_UPDATES', 'RESELLER_PROGRAM', name='consent_scope'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('proof_text', sa.String(length=500), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_consents_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_contact_id'), ['contact_id'], unique=False)

    op.create_table('conversation_summary',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('problem_type', sa.String(length=100), nullable=True),
    sa.Column('interest_level', sa.String(length=50), nullable=True),
    sa.Column('last_problem_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contacted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversation_stage', sa.String(length=50), nullable=False),
    sa.Column('message_count_at_last_summary', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_summary_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_summary'))
    )
    with op.batch_alter_table('conversation_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_summary_user_id'), ['user_id'], unique=True)

    op.create_table('conversations',
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'CLOSED', name='conversation_status'), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('assigned_agent', sa.String(length=255), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('interest_level', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_conversations_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_contact_id'), ['contact_id'], unique=False)

    op.create_table('cross_group_identities',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('first_seen_in_group', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_in_group', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_cross_group_identities_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cross_group_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_group_identities'))
    )
    with op.batch_alter_table('cross_group_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cross_group_identities_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cross_group_identities_user_id'), ['user_id'], unique=False)

    op.create_table('group_join_history',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('join_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], name=op.f('fk_group_join_history_account_id_telegram_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_join_history_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_join_history'))
    )
    with op.batch_alter_table('group_join_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_join_history_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_join_history_group_id'), ['group_id'], unique=False)

    op.create_table('influence_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('influence_score', sa.Float(), nullable=False),
    sa.Column('influence_level', sa.String(length=50), nullable=False),
    sa.Column('messages_sent_24h', sa.Integer(), nullable=False),
    sa.Column('replies_received', sa.Integer(), nullable=False),
    sa.Column('mentions_received', sa.Integer(), nullable=False),
    sa.Column('threads_started', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_influence_profiles_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_influence_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_influence_profiles'))
    )
    with op.batch_alter_table('influence_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_influence_profiles_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_influence_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('lead_profiles',
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('lifecycle_stage', sa.Enum('NEW', 'QUALIFIED', 'SUPPORT_ACTIVE', 'DEMO_SCHEDULED', 'CUSTOMER', 'RESELLER_INTEREST', 'CLOSED', name='lifecycle_stage'), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_lead_profiles_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_profiles'))
    )
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_profiles_contact_id'), ['contact_id'], unique=True)

    op.create_table('lead_value_scores',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ltv_score', sa.Float(), nullable=False),
    sa.Column('ltv_tier', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lead_value_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_value_scores'))
    )
    with op.batch_alter_table('lead_value_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_value_scores_user_id'), ['user_id'], unique=True)

    op.create_table('leads',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('intent_type', sa.String(length=50), nullable=True),
    sa.Column('intent_score', sa.Float(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('lead_strength', sa.String(length=50), nullable=True),
    sa.Column('first_contact', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_reply_sent', sa.Boolean(), nullable=False),
    sa.Column('dm_sent', sa.Boolean(), nullable=False),
    sa.Column('lead_temperature', sa.String(length=20), nullable=True),
    sa.Column('persona_id', sa.String(length=50), nullable=True),
    sa.Column('conversion_stage', sa.Enum('NEW', 'CONTACTED', 'RESPONDED', 'INTERESTED', 'CONVERTED', name='conversion_stage'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_leads_group_id_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_user_id'), ['user_id'], unique=False)

    op.create_table('problem_clusters',
    sa.Column('problem_type', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_problem_clusters_group_id_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_clusters'))
    )
    op.create_table('unified_conversations',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_unified_conversations_group_id_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_unified_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unified_conversations'))
    )
    with op.batch_alter_table('unified_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unified_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('conversion_predictions',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('conversion_probability', sa.Float(), nullable=False),
    sa.Column('conversion_tier', sa.String(length=50), nullable=False),
    sa.Column('opportunity_score_norm', sa.Float(), nullable=False),
    sa.Column('ltv_score_norm', sa.Float(), nullable=False),
    sa.Column('influence_score_norm', sa.Float(), nullable=False),
    sa.Column('engagement_score_norm', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_conversion_predictions_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversion_predictions'))
    )
    with op.batch_alter_table('conversion_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_predictions_lead_id'), ['lead_id'], unique=True)

    op.create_table('lead_conversations',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_conversations_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_conversations'))
    )
    with op.batch_alter_table('lead_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_conversations_lead_id'), ['lead_id'], unique=False)

    op.create_table('lead_opportunities',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('intent_score', sa.Integer(), nullable=False),
    sa.Column('influence_score', sa.Integer(), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=False),
    sa.Column('seller_density', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('priority_tier', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_opportunities_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_opportunities'))
    )
    with op.batch_alter_table('lead_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_opportunities_lead_id'), ['lead_id'], unique=True)

    op.create_table('messages',
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='message_direction'), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_group_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_draft', sa.Boolean(), nullable=False),
    sa.Column('human_approved', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_messages_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_reply_to_message_id'), ['reply_to_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_telegram_group_id'), ['telegram_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_telegram_message_id'), ['telegram_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_telegram_user_id'), ['telegram_user_id'], unique=False)

    op.create_table('tickets',
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('TECH_SUPPORT', 'BILLING', 'DEMO_REQUEST', 'RESELLER_INQUIRY', 'GENERAL', name='ticket_category'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='ticket_priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'RESOLVED', 'CLOSED', name='ticket_status'), nullable=False),
    sa.Column('first_response_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_tickets_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_tickets_conversation_id_conversations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_next_follow_up_at'), ['next_follow_up_at'], unique=False)

    op.create_table('follow_up_jobs',
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.Enum('SUPPORT_CHECKIN', 'DEMO_REMINDER', 'RESELLER_FOLLOW_UP', 'CONVERSATION_CLOSURE', name='follow_up_job_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='follow_up_job_status'), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_follow_up_jobs_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_follow_up_jobs_ticket_id_tickets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_up_jobs'))
    )
    with op.batch_alter_table('follow_up_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_up_jobs_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_jobs_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_jobs_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('message_analysis',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('classification', sa.Integer(), nullable=False),
    sa.Column('problem_type', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_analysis_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_analysis'))
    )
    with op.batch_alter_table('message_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_analysis_message_id'), ['message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_analysis_message_id'))

    op.drop_table('message_analysis')
    with op.batch_alter_table('follow_up_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_jobs_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_follow_up_jobs_run_at'))
        batch_op.drop_index(batch_op.f('ix_follow_up_jobs_contact_id'))

    op.drop_table('follow_up_jobs')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_next_follow_up_at'))
        batch_op.drop_index(batch_op.f('ix_tickets_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_contact_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_telegram_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_messages_telegram_group_id'))
        batch_op.drop_index(batch_op.f('ix_messages_reply_to_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_messages_contact_id'))

    op.drop_table('messages')
    with op.batch_alter_table('lead_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_opportunities_lead_id'))

    op.drop_table('lead_opportunities')
    with op.batch_alter_table('lead_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_conversations_lead_id'))

    op.drop_table('lead_conversations')
    with op.batch_alter_table('conversion_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_predictions_lead_id'))

    op.drop_table('conversion_predictions')
    with op.batch_alter_table('unified_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unified_conversations_user_id'))

    op.drop_table('unified_conversations')
    op.drop_table('problem_clusters')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_user_id'))
        batch_op.drop_index(batch_op.f('ix_leads_group_id'))

    op.drop_table('leads')
    with op.batch_alter_table('lead_value_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_value_scores_user_id'))

    op.drop_table('lead_value_scores')
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_profiles_contact_id'))

    op.drop_table('lead_profiles')
    with op.batch_alter_table('influence_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_influence_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_influence_profiles_group_id'))

    op.drop_table('influence_profiles')
    with op.batch_alter_table('group_join_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_join_history_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_join_history_account_id'))

    op.drop_table('group_join_history')
    with op.batch_alter_table('cross_group_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cross_group_identities_user_id'))
        batch_op.drop_index(batch_op.f('ix_cross_group_identities_group_id'))

    op.drop_table('cross_group_identities')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_contact_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('conversation_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_summary_user_id'))

    op.drop_table('conversation_summary')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_contact_id'))

    op.drop_table('consents')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_activity_events_contact_id'))

    op.drop_table('activity_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_user_id'))

    op.drop_table('users')
    with op.batch_alter_table('telegram_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_accounts_phone_number'))

    op.drop_table('telegram_accounts')
    op.drop_table('problem_trends')
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personas_name'))

    op.drop_table('personas')
    with op.batch_alter_table('metrics_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_snapshots_day'))

    op.drop_table('metrics_snapshots')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_telegram_id'))

    op.drop_table('groups')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_telegram_user_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('competitor_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_insights_competitor_name'))

    op.drop_table('competitor_insights')
    # ### end Alembic commands ###

