"""add lead scoring fields"""

revision = 'f0e68a1ede5e'
down_revision = '87511326a8b7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_leads')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engagement_score', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('recency_score', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('pattern_score', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('pattern_score')
        batch_op.drop_column('recency_score')
        batch_op.drop_column('engagement_score')

    op.create_table('external_leads',
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_leads'))
    )
    # ### end Alembic commands ###

